# 0. In linux do sudo su first (this is because of enviornment vars)
# 1. export APP_ENV=development
# 2. docker-compose build
# 3. docker-compose up -d


version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
      args:
        type_env: ${APP_ENV}
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/var/node
    networks:
      - nodeapp-network
    entrypoint:
      - /bin/bash


  postgres:
    image: postgres
    env_file:
      - ./docker/${APP_ENV}.env
    ports:
      - "5432:5432"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
